config/routes.rb
Rails.application.routes.draw do
  resources :people do
    resource :address
    collection { post :import }
  end
  get "secret", to: "people#secret"
  get 'cep', to: "cep#show"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :people, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cep.rb
require 'net/http'

class CEP
    attr_reader :cep, :logradouro, :complemento, :bairro, :localidade, :uf

    def initialize(cep)
        c = info(cep)
        @cep = c["cep"]
        @logradouro = c["logradouro"]
        @complemento = c["complemento"]
        @bairro = c["bairro"]
        @localidade = c["localidade"]
        @uf = c["uf"]
    end

    private

    def info(cep)
      ActiveSupport::JSON.decode(
        Net::HTTP.get(
          URI("https://viacep.com.br/ws/#{cep}/json/")
        )
      )
    end

end

app/models/person.rb
class Person < ApplicationRecord
    has_one :address
    accepts_nested_attributes_for :address
    validates_presence_of :name

    def self.to_csv
        CSV.generate do |csv|
            csv << column_names
            all.each do |person|
                csv << person.attributes.values_at(*column_names)
            end
        end
    end       

    def self.import(file)
        spreadsheet = Roo::Spreadsheet.open(file)
        spsh = spreadsheet.sheet("default")
        header = spsh.row(1)
        (2..spsh.last_row).each do |i|
            row = Hash[[header, spreadsheet.row(i)].transpose]
            person = find_by_id(row["id"]) || new
            person.attributes = row.to_hash
            person.save!
        end
        
    end
end
#/home/blue/Downloads/people.csv

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    def show
      @address = Person.find(params[:person_id]).address
      render json: @address
    end  
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    require 'csv'
    require 'iconv'
end

app/controllers/cep_controller.rb
class CepController < ApplicationController
  
    def show
      @cep = CEP.new(params[:cep])
      respond_to do |format|
        format.js { render layout: false }
      end
    end
    
end  

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  def import
    Person.import(params[:file])
    redirect_to people_url
  end

  def secret
  end

  # GET /people or /people.json
  def index
    @people = Person.all
    respond_to do |format|
      format.html
      format.json { render json: @people }
      format.csv { send_data @people.to_csv }
      format.xls
      format.xlsx
    end
  end

  # GET /people/1 or /people/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @person }
    end
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.build_address
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :age, address_attributes: [:cep, :logradouro, :complemento, :bairro, :localidade, :uf])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cep/show.js.erb
document.getElementById("logradouro").value = "<%= @cep.logradouro %>"
document.getElementById("complemento").value = "<%= @cep.complemento %>"
document.getElementById("bairro").value = "<%= @cep.bairro%>"
document.getElementById("localidade").value = "<%= @cep.localidade %>"
document.getElementById("uf").value = "<%= @cep.uf %>"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Persona</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <%= form.fields_for :address do |f| %>

    <div class="field">
      <%= f.label :cep %>
      <%= f.text_field :cep, id: "cep" %>
    </div>

    <%= link_to "Search", cep_path, id: "link", remote: true, local: false %>

    <div class="field">
      <%= f.label :logradouro %>
      <%= f.text_field :logradouro, id: "logradouro" %>
    </div>

    <div class="field">
      <%= f.label :complemento %>
      <%= f.text_field :complemento, id: "complemento" %>
    </div>

    <div class="field">
      <%= f.label :bairro %>
      <%= f.text_field :bairro, id: "bairro" %>
    </div>

    <div class="field">
      <%= f.label :localidade %>
      <%= f.text_field :localidade, id: "localidade"%>
    </div>

    <div class="field">
      <%= f.label :uf %>
      <%= f.text_field :uf, id: "uf" %>
    </div>

  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
    var c = document.getElementById("cep");
    var l = document.getElementById("link");
    c.addEventListener("change", function(){
      l.href = "<%= cep_path %>?cep=" + c.value
    });
</script>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="title">People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cep</th>
      <th>Logradouro</th>
      <th>Complemento</th>
      <th>Bairro</th>
      <th>Localidade</th>
      <th>UF</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <td><%= person.address.cep %></td>
        <td><%= person.address.logradouro %></td>
        <td><%= person.address.complemento %></td>
        <td><%= person.address.bairro %></td>
        <td><%= person.address.localidade %></td>
        <td><%= person.address.uf %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>
<%= link_to 'Secret', secret_path%>
<%= link_to 'Csv', people_path(format: :csv) %>
<%= link_to 'Xls', people_path(format: :xls) %>
<%= link_to 'Xlsx', people_path(format: :xlsx) %>

<%= form_tag import_people_path, multipart: true  do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/people/index.xls.erb
<head>
  <meta charset="utf-8"/>
</head>
<table>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Cep</th>
      <th scope="col">Logradouro</th>
      <th scope="col">Complemento</th>
      <th scope="col">Bairro</th>
      <th scope="col">Localidade</th>
      <th scope="col">UF</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
        <tr>
            <td><%= person.name %></td>
            <td><%= person.age %></td>
            <td><%= person.address.cep %></td>
            <td><%= person.address.logradouro %></td>
            <td><%= person.address.complemento %></td>
            <td><%= person.address.bairro %></td>
            <td><%= person.address.localidade %></td>
            <td><%= person.address.uf %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/people/index.xlsx.erb
<head>
  <meta charset="utf-8"/>
</head>
<table>
  <thead style="background-color:lightblue; color:white;">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Cep</th>
      <th scope="col">Logradouro</th>
      <th scope="col">Complemento</th>
      <th scope="col">Bairro</th>
      <th scope="col">Localidade</th>
      <th scope="col">UF</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
        <tr>
            <td><%= person.name %></td>
            <td><%= person.age %></td>
            <td><%= person.address.cep %></td>
            <td><%= person.address.logradouro %></td>
            <td><%= person.address.complemento %></td>
            <td><%= person.address.bairro %></td>
            <td><%= person.address.localidade %></td>
            <td><%= person.address.uf %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/secret.html.erb
<script>
$(document).ready(function(){
    $("#identificador").change(function(){
        $.ajax({url: "http://localhost:3000/people/"+this.value+".json"}).done(function(data){
            $("#namei").val(data.name);
            $("#agei").val(data.age);
            $("#cep").val(data.address.cep);
            $("#logradouro").val(data.address.logradouro);
            $("#complemento").val(data.address.complemento);
            $("#bairro").val(data.address.bairro);
            $("#localidade").val(data.address.localidade);
            $("#uf").val(data.address.uf);
            
        }).fail(function(){
            alert("Error");
        });        
    });
});
</script>

<%= form_with(url: people_path, local: true) do |form| %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: "identificador"%>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: "namei"%>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: "agei" %>
  </div>

  <%= form.fields_for :address do |f| %>

    <div class="field">
      <%= f.label :cep %>
      <%= f.text_field :cep, id: "cep" %>
    </div>

    <%= link_to "Search", cep_path, id: "link", remote: true, local: false %>

    <div class="field">
      <%= f.label :logradouro %>
      <%= f.text_field :logradouro, id: "logradouro" %>
    </div>

    <div class="field">
      <%= f.label :complemento %>
      <%= f.text_field :complemento, id: "complemento" %>
    </div>

    <div class="field">
      <%= f.label :bairro %>
      <%= f.text_field :bairro, id: "bairro" %>
    </div>

    <div class="field">
      <%= f.label :localidade %>
      <%= f.text_field :localidade, id: "localidade"%>
    </div>

    <div class="field">
      <%= f.label :uf %>
      <%= f.text_field :uf, id: "uf" %>
    </div>

  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>